### ISSUE TITLE
Could you add an example of using @Capacitor/Browser plugin?

### ISSUE THREAD

**Issue by RockBay** [ionic-team/portals-super-app-demo#11]
We have successfully make it work on Android, but are not able to make it work on iOS, being blocked by adding plugin to a specific portal.

Thanks You!

**Comment by Steven0351** [comment]
This demo uses Swift Package Manager, @capacitor/browser is not currently compatible with Swift Package Manager out of the box. I would suggest you add the native code directly to your project.
